apiVersion: v1
kind: Namespace
metadata:
  name: minio-standalone
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvminiostandalone
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: "/storage"
    server: "192.168.0.146"
---    
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: minio-standalone
  name: minio-pv-claim
  labels:
    app: minio-storage-claim
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: minio-standalone
  name: minio-deployment
spec:
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      nodeSelector:
        nfs: mounted
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: minio-pv-claim
      containers:
      - name: minio
        image: minio/minio
        args:
        - server
        - /storage
        env:
        - name: MINIO_ACCESS_KEY
          value: "minio_admin"
        - name: MINIO_SECRET_KEY
          value: "minio1234"
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: storage
          mountPath: "/storage"
---
apiVersion: v1
kind: Service
metadata:
  namespace: minio-standalone
  name: minio-service
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: minio