apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifacts-azure-blob-
spec:
  entrypoint: art-from-azure
  templates:
  - name: art-from-azure
    inputs:
      artifacts:
      - name: azure-asset
        path: /img.jpg
        azureBlob:
          defaultEndpointsProtocol: https
          endpointSuffix: blob.core.windows.net
          container: epiclabsastcont
          key: img.jpg
          accountNameSecret:
            name: azure-blob-credentials
            key: accountName
          accountKeySecret:
            name: azure-blob-credentials
            key: accountKey
    container: 
      image: debian
      command: [sh, -c]
      args: ["ls -l /img.jpg"]     

