apiVersion: v1
kind: List
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: delete-argo-workflows-cr
    annotations: 
      rbac.authorization.kubernetes.io/autoupdate: "true"
    labels:
      kubernetes.io/bootstrapping: rbac-defaults  
  rules:
  - apiGroups:
    - '*'
    resources:
    - 'workflows'
    verbs:
    - 'delete'
  - nonResourceURLs:
    - '*'
    verbs:
    - 'delete'

- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: delete-argo-workflows
    annotations: 
      rbac.authorization.kubernetes.io/autoupdate: "true"
    labels:
      kubernetes.io/bootstrapping: rbac-defaults  
  subjects:
  - kind: Group
    name: "system:masters"
    apiGroup: ""
  roleRef:
    kind: ClusterRole
    name:  delete-argo-workflows-cr
    apiGroup: rbac.authorization.k8s.io    

# - apiVersion: rbac.authorization.k8s.io/v1
#   kind: Role
#   metadata:
#     name: delete-argo-workflows-r
#     namespace: default
#   rules:
#   - apiGroups: [""]
#     resources: ["workflows"]
#     verbs: ["delete"]

# - apiVersion: rbac.authorization.k8s.io/v1
#   kind: RoleBinding
#   metadata:
#     name: role-grantor-binding
#     namespace: default
#   roleRef:
#     apiGroup: rbac.authorization.k8s.io
#     kind: ClusterRole
#     name: delete-argo-workflows-cr
#   subjects:
#   - apiGroup: rbac.authorization.k8s.io
#     kind: User
#     name: "system:serviceaccount:default:default"  