apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: pvnfs01
    spec:
      capacity:
        storage: 4Gi
      volumeMode: Filesystem
      accessModes:
        - ReadWriteMany
      persistentVolumeReclaimPolicy: Retain
      storageClassName: slow
      mountOptions:
        - hard
        - nfsvers=4.1
      nfs:
        path: "/nfs/general"
        server: "192.168.0.146"

  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: claimstorage
    spec:
      accessModes:
        - ReadWriteMany
      volumeMode: Filesystem
      resources:
        requests:
          storage: 4Gi
      storageClassName: slow

  - apiVersion: apps/v1 
    kind: Deployment
    metadata:
      name: nginx
    spec:
      selector:
        matchLabels:
          app: nginx
      replicas: 4
      template: 
        metadata:
          labels:
            app: nginx
        spec:
          containers:
          - name: nginx
            image: nginx:1.7.10
            volumeMounts:
            - name: nginx            
              mountPath: "/usr/share/nginx/html"
            ports:
            - name: http
              containerPort: 80
          volumes:
          - name: nginx
            persistentVolumeClaim:
              claimName: claimstorage
  - apiVersion: v1
    kind: Service
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      selector:
        app: nginx
      type: NodePort  
      ports:
      - name: http
        protocol: TCP
        port: 80
        targetPort: http
